# Generated by Django 3.0 on 2019-12-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tapa',
            name='url',
        ),
    ]
