# Generated by Django 3.0 on 2019-12-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapa', '0002_remove_tapa_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tapa',
            old_name='pub_date',
            new_name='date',
        ),
    ]
