# Generated by Django 3.0 on 2019-12-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapa', '0005_auto_20191226_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tapa',
            name='date',
            field=models.DateField(max_length=10),
        ),
    ]
